export const data=[
    {
        id:1,
        empName:'Seema',
        qualification:'MCA',
        salary:10000,
        department:'Coding'
    },
    {
        id:2,
        empName:'Seema1',
        qualification:'BCA',
        salary:20000,
        department:'Coding'
    },
    {
        id:3,
        empName:'Seema3',
        qualification:'BTECH',
        salary:30000,
        department:'Banking'
    }
]